workflows:
  ios-xper-release:
    name: Build iOS Automatique - Xper
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: 🛠️ Génération du projet iOS et désactivation forcée des sécurités Apple
        script: |
          # 1. Génération propre de la structure iOS
          flutter create --org com.bx --project-name xper --platforms=ios .
          
          # 2. Injection des permissions GPS obligatoires
          plutil -insert NSLocationWhenInUseUsageDescription -string "GPS nécessaire pour la vitesse." ios/Runner/Info.plist
          plutil -insert NSLocationAlwaysAndWhenInUseUsageDescription -string "GPS nécessaire en arrière-plan." ios/Runner/Info.plist
          
          # 3. LE CORRECTIF : Modification du fichier Xcode pour injecter une fausse Team
          sed -i '' 's/buildSettings = {/buildSettings = {\n\t\t\t\tCODE_SIGNING_ALLOWED = NO;\n\t\t\t\tCODE_SIGNING_REQUIRED = NO;\n\t\t\t\tCODE_SIGN_IDENTITY = "";\n\t\t\t\tDEVELOPMENT_TEAM = "DUMMYTEAM12";/g' ios/Runner.xcodeproj/project.pbxproj
      - name: 📦 Récupération des dépendances Flutter
        script: |
          flutter packages pub get
      - name: ⚙️ Configuration de CocoaPods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: 🏗️ Compilation brute de l'application (Bypass Xcode)
        script: |
          # On compile Xcode à accepter xcargs
          flutter build ios --release --no-codesign --xcargs "CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=\"\" DEVELOPMENT_TEAM=DUMMYTEAM12"
      - name: 🗜️ Création du fichier .ipa pour Sideloadly
        script: |
          # Packaging manuel de l'application non signée dans la structure attendue par Sideloadly
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          cd build/ios/iphoneos
          zip -r Xper.ipa Payload
    artifacts:
      - build/ios/iphoneos/Xper.ipa
