workflows:
  ios-build:
    name: iOS App Build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Preparation de l environnement iOS et simulation de l equipe
        script: |
          flutter create --org com.bx --project-name xper --platforms=ios .
          
          # Insertion des clés de configuration GPS
          plutil -insert NSLocationWhenInUseUsageDescription -string "GPS requis." ios/Runner/Info.plist
          plutil -insert NSLocationAlwaysAndWhenInUseUsageDescription -string "GPS requis." ios/Runner/Info.plist
          
          # Injection des paramètres pour contourner la signature Xcode
          echo "DEVELOPMENT_TEAM = NX78XYZ123" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGN_IDENTITY = -" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGNING_REQUIRED = NO" >> ios/Flutter/Release.xcconfig
          echo "CODE_SIGNING_ALLOWED = NO" >> ios/Flutter/Release.xcconfig
      - name: Recuperer les dependances Pub
        script: |
          flutter pub get
      - name: Compilation allegee pour iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Packager en IPA pour Sideloadly
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r Xper.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
