name: xper
description: "Application GPS Waze-like complète fonctionnant online et hors-ligne."
publish_to: 'none' # Empêche la publication accidentelle sur pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Indispensable pour le design natif iOS
  
  # Dépendances pour la cartographie et la géolocalisation
  flutter_map: ^7.0.2     # Le moteur de carte open-source
  latlong2: ^0.9.1        # Gestion des coordonnées géographiques
  geolocator: ^12.0.0     # Récupération de la position et de la vitesse par satellite
  intl: ^0.19.0           # Formatage de l'heure pour l'heure d'arrivée (ETA)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0   # Recommandé pour garder un code propre

flutter:
  uses-material-design: true
  # Si vous souhaitez intégrer des icônes ou des cartes de base hors-ligne à l'avenir,
  # décommentez les lignes ci-dessous :
  # assets:
  #   - assets/
